import { PARTNERS } from "@/demo/data";
import { OWNER_ID } from "@/mock/owner";

export const dynamic = "force-static";

/*
 * The service worker for the demo (/partners-demo and /app). Built from the
 * place list so the page list never goes stale.
 *
 * - On install it saves every demo page, and the scripts, styles, fonts and
 *   photos those pages use, so after the first visit it runs with no signal.
 * - While online it always fetches fresh (network first) and refreshes the copy.
 * - It leaves the marketing site alone: only the demo's own paths go through it.
 */
export function GET() {
  const slugs = [OWNER_ID, ...PARTNERS.map((p) => p.id)];
  const pages = [
    "/partners-demo",
    "/app",
    "/app/pass",
    "/app/owner",
    "/app/owner/setup",
    "/app/owner/next",
    ...slugs.flatMap((s) => [`/app/place/${s}`, `/app/redeem/${s}`]),
  ];
  const files = ["/app/manifest.webmanifest", "/app/icon-192.png", "/app/icon-512.png", "/app/icon-maskable.png", "/apple-icon"];

  const js = `/* Generated by src/app/app-sw.js/route.ts. Do not edit by hand. */
const CACHE = "t6p-demo-v2";
const PAGES = ${JSON.stringify(pages)};
const FILES = ${JSON.stringify(files)};
const OURS = /^\\/(app(\\/|$)|partners-demo|_next\\/|demo\\/|apple-icon)/;

// Every file a page needs: scripts, styles and photos in the HTML, and fonts inside the styles.
async function assetsOf(res, base) {
  const text = await res.text();
  const found = new Set();
  for (const m of text.matchAll(/["'(](\\/(?:_next\\/static|demo)\\/[^"'()\\s\\\\]+)/g)) found.add(m[1]);
  for (const m of text.matchAll(/url\\(([^)"']+)\\)/g)) found.add(new URL(m[1], base).pathname);
  return [...found];
}

// A redirected response can't be used to load a page, so keep a plain copy.
async function plain(res) {
  return res.redirected ? new Response(await res.blob(), { status: res.status, headers: res.headers }) : res;
}

async function precache() {
  const cache = await caches.open(CACHE);
  const seen = new Set();
  const queue = [...PAGES, ...FILES];
  while (queue.length) {
    const path = queue.shift();
    if (seen.has(path)) continue;
    seen.add(path);
    try {
      const res = await fetch(path, { cache: "no-cache" });
      if (!res.ok) continue;
      await cache.put(path, await plain(res.clone()));
      if (/\\.css$/.test(path) || PAGES.includes(path)) {
        for (const a of await assetsOf(res, self.location.origin + path)) if (!seen.has(a)) queue.push(a);
      }
    } catch (e) {
      /* offline during install: the next visit fills it in */
    }
  }
}

self.addEventListener("install", (e) => {
  self.skipWaiting();
  e.waitUntil(precache());
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !OURS.test(url.pathname)) return;
  // Page data for in-app navigation carries a changing ?_rsc= value; keep one copy per path.
  const key = url.searchParams.has("_rsc") || req.headers.get("RSC") ? url.pathname + "?rsc" : url.pathname.replace(/\\/$/, "") || "/";
  e.respondWith(
    fetch(req)
      .then((res) => {
        if (res.ok) {
          const copy = res.clone();
          plain(copy).then((p) => caches.open(CACHE).then((c) => c.put(key, p)));
        }
        return res;
      })
      .catch(async () => {
        const hit = await caches.match(key);
        if (hit) return hit;
        // No saved page data: let the app load the page itself, which is saved.
        if (key.endsWith("?rsc")) return Response.error();
        if (req.mode === "navigate") return (await caches.match("/partners-demo")) || Response.error();
        return Response.error();
      }),
  );
});
`;
  return new Response(js, { headers: { "Content-Type": "application/javascript; charset=utf-8" } });
}
